ALTER TABLE ARTICLES_VENDUS
    ADD COLUMN etat_vente VARCHAR(30) NOT NULL;

ALTER TABLE ARTICLES_VENDUS
    MODIFY date_debut_encheres TIMESTAMP;

ALTER TABLE ARTICLES_VENDUS
    MODIFY date_fin_encheres TIMESTAMP;

ALTER TABLE ENCHERES
    MODIFY date_enchere TIMESTAMP;

ALTER TABLE CATEGORIES
    ADD CONSTRAINT libelle_unique UNIQUE(libelle);
